# Generated by Django 4.1 on 2022-08-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joinorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_price', models.PositiveIntegerField()),
                ('menu_quantity', models.PositiveIntegerField()),
                ('join_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinorders.joinorder')),
            ],
        ),
    ]
