<<<<<<< HEAD
# Generated by Django 4.1 on 2022-08-11 08:21
=======
# Generated by Django 4.1 on 2022-08-10 08:55
>>>>>>> e6733ae62c51deb35e57f27f58b6d07b7c6df3b1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='order_status',
            field=models.CharField(choices=[('ING', 'Collecting'), ('FIN', 'Finished')], default='ING', max_length=3),
        ),
    ]
