# Generated by Django 4.1 on 2022-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='order_status',
            field=models.CharField(choices=[('ING', 'Collecting'), ('FIN', 'Finished')], default='ING', max_length=3),
        ),
    ]
