# Generated by Django 4.1 on 2022-08-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('boards', '0002_alter_board_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='order_status',
        ),
        migrations.AddField(
            model_name='board',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
        ),
    ]
