# Generated by Django 4.1 on 2022-08-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_order_status_board_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='menu',
        ),
    ]
