# Generated by Django 4.1 on 2022-08-12 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('max_joined_user', models.PositiveIntegerField(default=0)),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('order_status', models.CharField(choices=[('ING', 'Collecting'), ('FIN', 'Finished')], default='ING', max_length=3)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lead_user', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
