# Generated by Django 4.0.5 on 2022-08-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='brand',
            new_name='store',
        ),
    ]
