# Generated by Django 4.1 on 2022-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='social_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
